### ISSUE TITLE
Per your request: FFMPEG still not working

### ISSUE THREAD

**Issue by JSL101** [EpicenterHQ/epicenter#973]
It still comes back with "Failure to enumerate devices."  I'm on v.7.7.1.   I've tried reinstalling FFMPEG, adding the PATH manually, and so on.

### Platform

Windows

### Affected Component

Audio (recording/playback)

### Whispering Version

7.7.1

### Severity

Major (significant impact, no easy workaround)

### Checklist

- [x] I have searched existing issues to ensure this hasn't been reported
- [x] I have included all relevant information above

**Comment by Tamnac** [comment]
I'm getting the same issue, v7.7.1, windows 11. FFmpeg installed via scoop and is on the path, terminal commands work fine. Copying error below

```
{
  "message": "No recording devices found",
  "context": {
    "output": "ffmpeg version 8.0-full_build-www.gyan.dev Copyright (c) 2000-2025 the FFmpeg developers\r\n  built with gcc 15.2.0 (Rev8, Built by MSYS2 project)\r\n  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-lcms2 --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-libdvdnav --enable-libdvdread --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libopenjpeg --enable-libquirc --enable-libuavs3d --enable-libxevd --enable-libzvbi --enable-liboapv --enable-libqrencode --enable-librav1e --enable-libsvtav1 --enable-libvvenc --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxeve --enable-libxvid --enable-libaom --enable-libjxl --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-dxva2 --enable-d3d11va --enable-d3d12va --enable-ffnvcodec --enable-libvpl --enable-nvdec --enable-nvenc --enable-vaapi --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-openal --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libcodec2 --enable-libilbc --enable-libgsm --enable-liblc3 --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint --enable-whisper\r\n  libavutil      60.  8.100 / 60.  8.100\r\n  libavcodec     62. 11.100 / 62. 11.100\r\n  libavformat    62.  3.100 / 62.  3.100\r\n  libavdevice    62.  1.100 / 62.  1.100\r\n  libavfilter    11.  4.100 / 11.  4.100\r\n  libswscale      9.  1.100 /  9.  1.100\r\n  libswresample   6.  1.100 /  6.  1.100\r\n[dshow @ 0000020099a85b40] \"Laptop Camera\" (video)\r\n[dshow @ 0000020099a85b40]   Alternative name \"@device_pnp_\\\\?\\usb#vid_0bda&pid_5634&mi_00#6&125ae00b&0&0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\\global\"\r\n[dshow @ 0000020099a85b40] \"Microphone Array (2- Realtek(R) Audio)\" (audio)\r\n[dshow @ 0000020099a85b40]   Alternative name \"@device_cm_{33D9A762-90C8-11D0-BD43-00A0C911CE86}\\wave_{3C041AA4-FB35-4D69-A685-01087EDB6E74}\"\r\nError opening input file dummy.\r\n"
  },
  "name": "RecorderServiceError"
}
```

This issue is the successor of #762

**Comment by braden-w** [comment]
Hey @Tamnac and @JamesTheAwesomeDude, thank you for reporting this issue!

I've identified and fixed the root causes. There were actually two problems:

1. **Device parsing bug**: The regex pattern wasn't matching FFmpeg's output format because it didn't account for the `[dshow @ 0x...]` prefix that FFmpeg adds to device listings. This caused the parser to return zero devices even though FFmpeg successfully found them.

2. **DirectShow syntax issue**: The recording command wasn't using the correct DirectShow parameter format. DirectShow requires `audio="Device Name"` where the quotes are part of the parameter syntax.

I've created PR #985 with fixes for both issues. This should resolve the "No recording devices found" error and allow Windows users to record with device names that contain spaces and special characters like "Microphone Array (2- Realtek(R) Audio)".

Thank you for providing the detailed error logs - they were essential for identifying the issue!

**Comment by JSL101** [comment]
I hate to be the one to say this, but it's still not working.  I've done everything: reinstalled FFMPEG, set the PATH, and so on, and still I get "Failed to enumerate devices".  The complete error message is:

{
  "message": "No recording devices found",
  "context": {
    "output": "ffmpeg version 8.0-full_build-www.gyan.dev Copyright (c) 2000-2025 the FFmpeg developers\r\n  built with gcc 15.2.0 (Rev8, Built by MSYS2 project)\r\n  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-lcms2 --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-libdvdnav --enable-libdvdread --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libopenjpeg --enable-libquirc --enable-libuavs3d --enable-libxevd --enable-libzvbi --enable-liboapv --enable-libqrencode --enable-librav1e --enable-libsvtav1 --enable-libvvenc --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxeve --enable-libxvid --enable-libaom --enable-libjxl --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-dxva2 --enable-d3d11va --enable-d3d12va --enable-ffnvcodec --enable-libvpl --enable-nvdec --enable-nvenc --enable-vaapi --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-openal --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libcodec2 --enable-libilbc --enable-libgsm --enable-liblc3 --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint --enable-whisper\r\n  libavutil      60.  8.100 / 60.  8.100\r\n  libavcodec     62. 11.100 / 62. 11.100\r\n  libavformat    62.  3.100 / 62.  3.100\r\n  libavdevice    62.  1.100 / 62.  1.100\r\n  libavfilter    11.  4.100 / 11.  4.100\r\n  libswscale      9.  1.100 /  9.  1.100\r\n  libswresample   6.  1.100 /  6.  1.100\r\n[dshow @ 00000191ffa35c40] \"Integrated Webcam\" (video)\r\n[dshow @ 00000191ffa35c40]   Alternative name \"@device_pnp_\\\\?\\usb#vid_0c45&pid_6713&mi_00#6&1ede488b&1&0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\\global\"\r\n[dshow @ 00000191ffa35c40] \"Microphone (Realtek Audio)\" (audio)\r\n[dshow @ 00000191ffa35c40]   Alternative name \"@device_cm_{33D9A762-90C8-11D0-BD43-00A0C911CE86}\\wave_{25B621BB-33DE-41E6-BAAF-6D62CF16CC40}\"\r\nError opening input file dummy.\r\n"
  },
  "name": "RecorderServiceError"
}

**Comment by Tamnac** [comment]
@JSL101 wait for the pr above to actually be merged and released, then we'll see

**Comment by JSL101** [comment]
> [@JSL101](https://github.com/JSL101) wait for the pr above to actually be merged and released, then we'll see

Ah, my apologies.  I thought It was merged in 7.7.2.  My mistake. I’ll wait patiently.

**Comment by braden-w** [comment]
Sorry guys, gonna test this later and hopefully merge in 7.7.3! I realize that the issue might not be solved, need to run my virtual machine and hopefully see if it is fixed then.

**Comment by quickreactor** [comment]
Still not fixed in 7.9.0!

**Comment by hi4nik** [comment]
Still not fixed in 7.11.0

**Comment by braden-w** [comment]
Hey @JSL101, @Tamnac, @quickreactor, and @hi4nik, thanks for the logs and the follow-ups across releases!

This thread was about the old Windows FFmpeg recorder path: DirectShow device enumeration, `dummy` input parsing, and building the right FFmpeg input string. I tried to fix that path in #985, but Whispering has since moved in a cleaner direction.

That change is part of the audio-pipeline cleanup in #1816, #1826, and #1828:

```txt
#1816  remove FFmpeg as a recording method
#1826  replace FFmpeg local decode with Symphonia + libopus
#1828  replace FFmpeg upload compression with Rust Opus
```

The new shape is:

```txt
recording      -> CPAL or MediaRecorder
local decode   -> Symphonia + libopus
cloud upload   -> Rust Opus encoder
```

I am closing this now as obsolete. That should remove the old FFmpeg failure mode. If Windows recording still fails on the new release, please open a fresh issue with the current app version and exact error text so we can debug the new path directly.

Thanks again for the patience here. The old FFmpeg path was a lot rougher than it should have been, and I appreciate everyone sticking with the reports across releases.
